### PR TITLE
Improve addons search command

### PR DESCRIPTION
**Pull request by tymmesyde**
Allow to search for id and convert query to lowercase

### CODE REVIEW

**Comment by sleeyax** [comment]
Looks good but I wonder how often people would actually search by id?

**Comment by tymmesyde** [comment]
I just though it would widen the search results, but if you think that's not needed i'll remove it !

**Comment by sleeyax** [comment]
Hmm perhaps it makes more sense to search on description instead of id? Way I see it ID is mostly useful to devs and in this context could be very obscure and result in false positive search results.

**Comment by tymmesyde** [comment]
Yeah that makes more sense in the user context

**Pull request merged**
